# Data Understanding

## Objective

The objective of this notebook is to understand the structure, characteristics, and business relevance of the DataCo Supply Chain dataset before performing data cleaning and analysis.

This notebook focuses on:
- Understanding the dataset structure
- Exploring business entities
- Identifying measures and dimensions
- Defining business KPIs
- Assessing initial data quality
- Preparing the dataset for further analysis

In [1]:
# Import Liabraries
import numpy as np 
import pandas as pd

In [2]:
# Load Dataset
df = pd.read_csv('D:\Supply Chain\Dataset.csv', encoding='latin1')

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\nanga\AppData\Local\Temp\ipykernel_1008\696363885.py:2: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv('D:\Supply Chain\Dataset.csv', encoding='latin1')

# Dataset Overview

## Dataset Description

The **DataCo Supply Chain Dataset** is a structured retail supply chain dataset that contains transactional, operational, and customer-related data generated throughout the order fulfillment process. The dataset combines information from multiple business functions, including customer management, product management, sales, order processing, shipping, delivery, and financial performance.

Each record represents an individual order item transaction, enabling detailed analysis of supply chain operations at a transactional level.

The dataset provides a comprehensive view of business activities, making it suitable for evaluating operational efficiency, customer purchasing behavior, sales performance, profitability, logistics performance, and regional market trends.

---

## Business Functions Represented

The dataset captures data across multiple business functions:

- Customer Management
- Product Management
- Order Management
- Sales & Revenue
- Profitability
- Logistics & Shipping
- Delivery Operations
- Regional & Market Performance

---

## Core Business Entities

The dataset contains information related to the following business entities:

- Customers
- Orders
- Products
- Categories
- Departments
- Shipping
- Delivery
- Markets
- Regions

---

## Business Value

This dataset enables end-to-end supply chain analytics by supporting:

- Sales Performance Analysis
- Profitability Analysis
- Customer Analytics
- Product Performance Analysis
- Delivery Performance Monitoring
- Shipping Efficiency Evaluation
- Business Intelligence Reporting
- Data-Driven Decision Making

In [3]:
df.shape

(180519, 53)

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,02-03-2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [6]:
DataDiscription = pd.read_csv('D:\Supply Chain\DescriptionDataCoSupplyChain.csv')
DataDiscription

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\nanga\AppData\Local\Temp\ipykernel_1008\2492070310.py:1: SyntaxWarning: invalid escape sequence '\S'
  DataDiscription = pd.read_csv('D:\Supply Chain\DescriptionDataCoSupplyChain.csv')

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer
5,Delivery Status,: Delivery status of orders: Advance shipping...
6,Late_delivery_risk,: Categorical variable that indicates if send...
7,Category Id,: Product category code
8,Category Name,: Description of the product category
9,Customer City,: City where the customer made the purchase
10,Customer Country,: Country where the customer made the purchase
11,Customer Email,: Customer's email
12,Customer Fname,: Customer name
13,Customer Id,: Customer ID
14,Customer Lname,: Customer lastname
15,Customer Password,: Masked customer key
16,Customer Segment,": Types of Customers: Consumer , Corporate , ..."
17,Customer State,: State to which the store where the purchase...
18,Customer Street,: Street to which the store where the purchas...
19,Customer Zipcode,: Customer Zipcode
20,Department Id,: Department code of store
21,Department Name,: Department name of store
22,Latitude,: Latitude corresponding to location of store
23,Longitude,: Longitude corresponding to location of store
24,Market,: Market to where the order is delivered : Af...
25,Order City,: Destination city of the order
26,Order Country,: Destination country of the order
27,Order Customer Id,: Customer order code
28,order date (DateOrders),: Date on which the order is made
29,Order Id,: Order code
30,Order Item Cardprod Id,: Product code generated through the RFID reader
31,Order Item Discount,: Order item discount value
32,Order Item Discount Rate,: Order item discount percentage
33,Order Item Id,: Order item code
34,Order Item Product Price,: Price of products without discount
35,Order Item Profit Ratio,: Order Item Profit Ratio
36,Order Item Quantity,: Number of products per order
37,Sales,: Value in sales
38,Order Item Total,: Total amount per order
39,Order Profit Per Order,: Order Profit Per Order
40,Order Region,: Region of the world where the order is deli...
41,Order State,: State of the region where the order is deli...
42,Order Status,": Order Status : COMPLETE , PENDING , CLOSED ..."
43,Product Card Id,: Product code
44,Product Category Id,: Product category code
45,Product Description,: Product Description
46,Product Image,: Link of visit and purchase of the product
47,Product Name,: Product Name
48,Product Price,: Product Price
49,Product Status,: Status of the product stock :If it is 1 not...
50,Shipping date (DateOrders),: Exact date and time of shipment
51,Shipping Mode,: The following shipping modes are presented ...

## Business Metrics

### Measures (Numerical)

- Sales
- Order Item Total
- Order Profit Per Order
- Benefit per Order
- Order Item Quantity
- Product Price
- Order Item Discount
- Order Item Discount Rate

### Dimensions (Categorical)

- Customer
- Product
- Category
- Department
- Market
- Region
- Shipping Mode
- Delivery Status
- Order Status
- Order Date
- Shipping Date

## Key Performance Indicators (KPIs)

| KPI | Description | Business Importance |
|------|-------------|--------------------|
| Total Sales | Total revenue generated from all orders | Measures business growth |
| Total Profit | Total profit earned from completed orders | Measures financial performance |
| Profit Margin | Profit earned relative to sales | Evaluates profitability |
| Average Order Value | Average revenue generated per order | Measures customer purchasing behaviour |
| Order Volume | Total number of orders | Measures business demand |
| Late Delivery Rate | Percentage of delayed deliveries | Evaluates logistics efficiency |
| On-Time Delivery Rate | Percentage of orders delivered on schedule | Measures delivery performance |
| Average Shipping Time | Average actual shipping duration | Measures operational efficiency |
| Sales by Market | Revenue generated across different markets | Identifies high-performing markets |
| Profit by Category | Profit contribution by product category | Supports product portfolio decisions |

## Initial Business Expectations

Based on the dataset structure, the following hypotheses will be validated during analysis:

- Some product categories are expected to generate higher sales but lower profit margins.
- Delivery delays may vary across shipping modes and geographical regions.
- Certain markets may contribute significantly more revenue than others.
- High sales volume does not necessarily translate into high profitability.
- Customer segments may exhibit different purchasing patterns.

# Data Quality Assessment Plan

Before performing exploratory data analysis, the dataset will be evaluated for:

- Missing values
- Duplicate records
- Incorrect data types
- Invalid values
- Inconsistent categorical values
- Outliers

In [7]:
Null_values = df.isnull().sum() 
Null_values[Null_values > 0]

Customer Lname              8
Customer Zipcode            3
Order Zipcode          155679
Product Description    180519
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [10]:
df.describe(include="object")

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Lname,Customer Password,Customer Segment,...,Order City,Order Country,order date (DateOrders),Order Region,Order State,Order Status,Product Image,Product Name,shipping date (DateOrders),Shipping Mode
count,180519,180519,180519,180519,180519,180519,180519,180511,180519,180519,...,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519
unique,4,4,50,563,2,1,782,1109,1,3,...,3597,164,65752,23,1089,9,118,118,63701,4
top,DEBIT,Late delivery,Cleats,Caguas,EE. UU.,XXXXXXXXX,Mary,Smith,XXXXXXXXX,Consumer,...,Santo Domingo,Estados Unidos,12/14/2016 12:29,Central America,Inglaterra,COMPLETE,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,01-05-2016 05:58,Standard Class
freq,69295,98977,24551,66770,111146,180519,65150,64104,180519,93504,...,2211,24840,5,28341,6722,59491,24515,24515,10,107752

In [11]:
df.nunique()

Type                                  4
Days for shipping (real)              7
Days for shipment (scheduled)         4
Benefit per order                 21998
Sales per customer                 2927
Delivery Status                       4
Late_delivery_risk                    2
Category Id                          51
Category Name                        50
Customer City                       563
Customer Country                      2
Customer Email                        1
Customer Fname                      782
Customer Id                       20652
Customer Lname                     1109
Customer Password                     1
Customer Segment                      3
Customer State                       46
Customer Street                    7458
Customer Zipcode                    995
Department Id                        11
Department Name                      11
Latitude                          11250
Longitude                          4487
Market                                5
Order City                         3597
Order Country                       164
Order Customer Id                 20652
order date (DateOrders)           65752
Order Id                          65752
Order Item Cardprod Id              118
Order Item Discount                1017
Order Item Discount Rate             18
Order Item Id                    180519
Order Item Product Price             75
Order Item Profit Ratio             162
Order Item Quantity                   5
Sales                               193
Order Item Total                   2927
Order Profit Per Order            21998
Order Region                         23
Order State                        1089
Order Status                          9
Order Zipcode                       609
Product Card Id                     118
Product Category Id                  51
Product Description                   0
Product Image                       118
Product Name                        118
Product Price                        75
Product Status                        1
shipping date (DateOrders)        63701
Shipping Mode                         4
dtype: int64

# Summary

In this phase, the DataCo Supply Chain dataset was explored to understand its structure, business entities, measures, dimensions, and key performance indicators. An initial assessment of data quality was also performed to identify potential issues that will be addressed in the next phase.

The insights gained during this stage establish a strong foundation for data cleaning, exploratory data analysis, statistical analysis, and predictive modelling.